### PR TITLE
updating proptypes

### PR DESCRIPTION
**Pull request by cpeddecord**
haven't made the jump to latest version of this package but we're looking to move to React 16 so...

### CODE REVIEW

**Comment by n1ru4l** [comment]
@cpeddecord Could you fix the issues? Looking forward getting this merged. I also want to upgrade to React 16!

**Comment by ctrlplusb** [comment]
Closing this as we are using prop-types package now. Thanks!

**Comment by cpeddecord** [comment]
@ctrlplusb this was on your 0.x.x branch, not master.

**Comment by ctrlplusb** [comment]
Ah oki I missed that. I will look into it again. Apologies.

**Comment by cpeddecord** [comment]
@ctrlplusb I'm not sure why there are merge conflicts on this PR... any help would be appreciated.

**Pull request closed without merging**
